before:
  hooks:

builds:
  - id: aserto-idp-plugin-azuread-amd64
    main: ./cmd/aserto-idp-plugin-azuread
    binary: aserto-idp-plugin-azuread
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto-idp-plugin-azuread/pkg/config.ver={{.Version}}
      - -X github.com/aserto-dev/aserto-idp-plugin-azuread/pkg/config.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto-idp-plugin-azuread/pkg/config.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: aserto-idp-plugin-azuread-arm64
    main: ./cmd/aserto-idp-plugin-azuread
    binary: aserto-idp-plugin-azuread
    goos:
      - darwin
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto-idp-plugin-azuread/pkg/config.ver={{.Version}}
      - -X github.com/aserto-dev/aserto-idp-plugin-azuread/pkg/config.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto-idp-plugin-azuread/pkg/config.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - README.md
    name_template: "aserto-idp-plugin-azuread{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

blobs:
  - provider: gs
    bucket: aserto-idp-cli
    folder: "plugins/aserto-idp-plugin-azuread/{{ .Major }}/{{ .Version }}"

release:
  github:
    owner: aserto-dev
    name: aserto-idp-plugin-azuread

  draft: false
  prerelease: false
  name_template: "aserto-idp-plugin-azuread {{.Tag}}"